### ISSUE TITLE
Travelnet node remains after being destroyed by destructive mob.

### ISSUE THREAD

**Issue by Cat5TV** [Sokomine/travelnet#13]
If unprotected Travelnet node is destroyed by Dungeon Master, the node is removed but the travelnet continues to operate.

According to the mod author, travelnet requires an after_dig function to clear travelnet from grid.

Thanks!

**Comment by HybridDog** [comment]
it's possible to get nodes in unloaded chunks, see https://github.com/HybridDog/minetest-teleporters/blob/hversion/teleporters/init.lua#L23

**Comment by Sokomine** [comment]
There is now support for the on_blast function used by TNT and (hopefully) the aggressive mobs. Travelnets and elevators ought to be immune from beeing destroyed by them. They are nodes that belong to players and cannot be digged by others.
If you really feel that mobs ought to be able to destroy travelnet boxes, you may add travelnet.remove_box(..) to the on_blast function. You'd still have to supply a player object to the function in order for it to be able to send its messages to the player.

**Comment by HybridDog** [comment]
@Sokomine, it's possible to test if the target travelnet exists before teleporting the player there: You can load the mapblock with vmanip and then minetest.get_node_or_nil returns nil only if the map isn't generated there.
https://github.com/HybridDog/minetest-teleporters/blob/hversion/teleporters/init.lua#L24
