### ISSUE TITLE
Missing file to clarify licenses

### ISSUE THREAD

**Issue by SnarkBoojum** [Sokomine/travelnet#21]
The .lua files have headers and give a license, but for the textures and models, there is no such thing. I would like to package travelnet for Debian, but I can't do that without clear licenses on each and every file.

Thanks!

**Comment by HybridDog** [comment]
You may also want to merge #19 before packaging.

**Comment by Sokomine** [comment]
Thanks for alerting me to that PR! #19 has been merged. VanessaE (who provided the textures and models) released them as CC0. The rest is GPLv3 as before. Also added a copy of the GPL.
Done in fc914aa804ed4f557608191bb137a597d375af5a
