### ISSUE TITLE
Could not set owner of travelnet

### ISSUE THREAD

**Issue by MuhdNurHidayat** [Sokomine/travelnet#25]
I have all privs needed but it would not let me set the owner of travelnet network.

The mod did not give any error, it just straight away save the travelnet under my name, regardless if I write existing online, existing offline or non-existing player's name in the "Owned by" field in configuration. It will still save under my name as the owner under all conditions.

Using fresh install of travelnet mod, cloned directly from GitHub, tested on:
- 0.4.16-stable localhost multiplayer on Windows 8.1
- 0.4.17-dev dedicated server on Debian 8

**Comment by Sokomine** [comment]
Ups! There was indeed a bug. Thank you for reporting! It ought to be fixed now.
