### ISSUE TITLE
tnt proof

### ISSUE THREAD

**Issue by 00c** [Sokomine/travelnet#26]
When tnt explode travelbox disappear. 
Is there a way to protect them from tnt

**Comment by codexp** [comment]
Hasn't it been solved in issue #13?

**Comment by 00c** [comment]
I meant something different. When tnt explode travlbox should not disappear. If that's possible

**Comment by codexp** [comment]
maybe there should be a setting for that

**Comment by Sokomine** [comment]
Travelnet stations are now immune to TNT blasts. They remain standing.
