### ISSUE TITLE
No longer allows updating of travelnets or assigning ownership (after Jan 2018)

### ISSUE THREAD

**Issue by redblade7** [Sokomine/travelnet#27]
Hi,

After updating the mods on my server recently, I am unable to update travelnets with new stations. The station is added to the travelnet at that station only, other stations on the travelnet are not updated with the new stations when you punch them.

Also, I have an account which can add stations to other users' travelnets. This is no longer possible, and the new dialog's ownership field has absolutely no effect (it's always the user who placed the station).

The bug happened between January 15, 2018 and March 25, 2018.

Thank you!

**Comment by redblade7** [comment]
Punching travelnets has no effect anymore

**Comment by redblade7** [comment]
Some (but not all) stations have the move up/down options.

**Comment by codexp** [comment]
I confirm, there is a bug with updating travelnet boxes, punching them does not work anymore.

**Comment by codexp** [comment]
Why not placing an "Update" button on the form?

**Comment by HybridDog** [comment]
In my opinion boxes should be updated automatically.

**Comment by codexp** [comment]
I believe there is a config for enabling automatic update of boxes, but it uses abm.

**Comment by codexp** [comment]
I've figured out why punching does not work. This happens in creative mode when not wielding with **axe** or **shovel** (update works with those).
But if you have bare hands or hold anything else (except **pickaxe**), this results in `tool_capabilities["groupcaps"]["cracky"]` having a table with this values:

```
{
	times = {
		42,
		42,
		42
	},
	uses = 0,
	maxlevel = 256
}
```
thus the `travelnet.check_if_trying_to_dig` function returns falsely `TRUE`.

**Comment by redblade7** [comment]
I can confirm that it only affects my creative server (Creative Gardens) and using the axe works properly.

I tried the ABM but other players complained of being occasionally flooded with messages about it.

**Comment by Sokomine** [comment]
There have been issues with distinguishing between punching and digging - in particular regarding creative mode. For a while, a diamond pick was necessary to dig the stations. However, the users did not like this option.

The current solution is a "Remove station" button. Punching updates the station, and clicking on that button digs it and places it into your inventory.

I've also fixed a bug with attaching travelnets to nets of other players not working anymore.

**Comment by Sokomine** [comment]
The bugs ought to be fixed. Please don't hesistate to open a new issue if any new errors or bugs occour or anything ought to be changed in the newest version.

**Comment by HybridDog** [comment]
Btw: Since minetest 5.0.0, there's the minetest.load_area function.
